### ISSUE TITLE
Apache Phoenix JDBC driver support

### ISSUE THREAD

**Issue by nblagodarnyi** [ClickHouse/clickhouse-jdbc-bridge#11]
Please add Apache Phoenix JDBC driver support. When I try to use it with bridge, I get 

2019-11-14 14:35:09,135 [ HTTP Handler-30 ] {ColumnsInfoServlet} <ERROR> - 
java.lang.UnsupportedOperationException
	at org.apache.phoenix.jdbc.PhoenixConnection.setClientInfo(PhoenixConnection.java:1010)
	at ru.yandex.clickhouse.jdbcbridge.db.jdbc.BridgeConnectionManager.get(BridgeConnectionManager.java:81)
	at ru.yandex.clickhouse.jdbcbridge.servlet.ColumnsInfoServlet.doPost(ColumnsInfoServlet.java:39)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at ru.yandex.clickhouse.jdbcbridge.servlet.RequestLogger.doFilter(RequestLogger.java:32)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:205)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

**Environment**
_OS_: NAME="Ubuntu" VERSION="16.04.5 LTS (Xenial Xerus)"
_JAVA_: openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
_ClickHouse_: version 19.16.2.2 (official build)
_Phoenix jdbc_: phoenix-4.14.2-HBase-1.4-client.jar
_Run_: java -jar clickhouse-jdbc-bridge-1.0.jar --datasources /etc/clickhouse-jdbc-bridge/datasources.properties --driver-path /var/lib/clickhouse-jdbc-bridge --err-log-path /etc/clickhouse-jdbc-bridge/error.log --log-path /etc/clickhouse-jdbc-bridge/bridge.log

**Comment by zhicwu** [comment]
I believe this has been fixed in 1.x.
