### ISSUE TITLE
connect exception

### ISSUE THREAD

**Issue by jjtjiang** [ClickHouse/clickhouse-jdbc-bridge#47]
i have start it  jdbc-bridge ，and it is running ，but happen "DB::Exception: jdbc-bridge is not running. ",thanks.
Code: 410, e.displayText() = DB::Exception: jdbc-bridge is not running. Please, start it manually (version 20.4.4.18 (official build))

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:135)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:492)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:427)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:419)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:779)

	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2966)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:111)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:170)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:109)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3580)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by xchf** [comment]
When I set --listen-hose 0.0.0.0 is succes.

**Comment by jjtjiang** [comment]
thanks ,have you ever set other settings about clickhouse ? it doesn't work when I set --listen-hose 0.0.0.0

**Comment by xchf** [comment]
1.java -jar /home/app/clickhouse-jdbc-bridge/clickhouse-jdbc-bridge-1.0.jar --driver                          -path /var/lib/clickhouse-jdbc-bridge --listen-host 0.0.0.0
2.netstat -tunlp
tcp6       0      0 :::9019                 :::*                    LISTEN      32463/java
3.config.xml
accept connections both with IPv4 and IPv6 from everywhere
 <listen_host>::</listen_host>

**Comment by zhicwu** [comment]
Is this still an issue? I'll close this one if no update next week.
