### ISSUE TITLE
mysql DECIMAL not support 

### ISSUE THREAD

**Issue by LXHING999** [ClickHouse/clickhouse-jdbc-bridge#7]
java.sql.SQLException: Can not map SQL type 3 (DECIMAL) to ClickHouse
	at ru.yandex.clickhouse.jdbcbridge.db.clickhouse.ClickHouseConverter.getInstructionBySQLType(ClickHouseConverter.java:91)
	at ru.yandex.clickhouse.jdbcbridge.db.clickhouse.ClickHouseConverter.getBySQLType(ClickHouseConverter.java:66)
	at ru.yandex.clickhouse.jdbcbridge.db.clickhouse.ClickHouseConverter.getColumnsDDL(ClickHouseConverter.java:107)
	at ru.yandex.clickhouse.jdbcbridge.servlet.ColumnsInfoServlet.doPost(ColumnsInfoServlet.java:53)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at ru.yandex.clickhouse.jdbcbridge.servlet.RequestLogger.doFilter(RequestLogger.java:32)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:205)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zhicwu** [comment]
Decimal is supported now. Will close this one after 2.0 release

**Comment by zhicwu** [comment]
Below works for me using 2.0.0:
```sql
select * from jdbc('mariadb?mutation', 'drop table if exists t')
select * from jdbc('mariadb?mutation', 'create table if not exists t(d decimal(10,3))')
select * from jdbc('mariadb?mutation', 'insert into t values(1.23)')
select * from jdbc('mariadb', 'select * from t')

select * from jdbc('mariadb', 'v Decimal(10,3)', 'select 1.234 as v')
```
