### ISSUE TITLE
Does 2.0 support connecting to oracle

### ISSUE THREAD

**Issue by gdnxdcs** [ClickHouse/clickhouse-jdbc-bridge#89]
When I connect to Oracle through clickhouse-jdbc-bridge2.0, it reports an error.Does 2.0 support connecting to oracle.
The details are as follows：
NamedDataSource [oracle] file oracle.json:
{
  "$schema": "../datasource.jschema",
  "oracle": {
    "driverUrls": [
        "/smartbiMpp/jdbc-bridge/config/datasources/drivers/oracle/oracle.jar"
],
    "driverClassName": "oracle.jdbc.driver.OracleDriver",
    "jdbcUrl": "jdbc:oracle:thin:@192.168.153.1:1521/orcl",
    "username": "smartbi",
    "password": "smartbi",
    "maximumPoolSize": 5
  }
}
sql:
select count(1) dd  from jdbc('oracle', 'smartbi', 'test')
error log:
Code: 86. DB::Exception: Received from 192.168.153.128:9000. DB::Exception: Received error from remote server /columns_info?connection_string=oracle&schema=smartbi&table=test. HTTP status code: 500 Internal Server Error, body: NamedDataSource [oracle] does not exist!.

when startup clickhouse-jdbc-bridge2.0,the log is :
2021-01-27 11:06:07.007 [vert.x-eventloop-thread-0] [INFO ] {Utils:940} - Loading JSON from file [config/httpd.json]...
2021-01-27 11:06:07.007 [vert.x-eventloop-thread-0] [WARN ] {Utils:949} - Failed to load JSON from file config/httpd.json
2021-01-27 11:06:07.007 [vert.x-eventloop-thread-0] [INFO ] {JdbcBridgeVerticle:270} - Starting web server...
2021-01-27 11:06:07.007 [vert.x-worker-thread-1] [INFO ] {JsonFileRepository:75} - No NamedSchema configuration found
2021-01-27 11:06:07.007 [vert.x-worker-thread-1] [INFO ] {JsonFileRepository:75} - No NamedQuery configuration found
2021-01-27 11:06:07.007 [vert.x-eventloop-thread-0] [INFO ] {JdbcBridgeVerticle:274} - Server http://0.0.0.0:9019 started in 1101 ms
2021-01-27 11:06:07.007 [vert.x-worker-thread-2] [INFO ] {JsonFileRepository:87} - Loading NamedDataSource configuration...
2021-01-27 11:06:07.007 [vert.x-worker-thread-2] [INFO ] {BaseRepository:206} - Adding NamedDataSource(id=mssql)...
2021-01-27 11:06:08.008 [vert.x-worker-thread-2] [WARN ] {DriverDataSource:70} - Registered driver with driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver was not found, trying direct instantiation.
Jan 27, 2021 11:06:08 AM com.microsoft.sqlserver.jdbc.TDSChannel enableSSL
WARNING: TLSv1 was negotiated. Please update server and client to use TLSv1.2 at minimum.
2021-01-27 11:06:08.008 [vert.x-worker-thread-2] [INFO ] {BaseRepository:206} - Adding NamedDataSource(id=mysql)...
2021-01-27 11:06:08.008 [vert.x-worker-thread-2] [WARN ] {DriverDataSource:70} - Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
2021-01-27 11:06:09.009 [vert.x-worker-thread-2] [INFO ] {BaseRepository:206} - Adding NamedDataSource(id=oracle)...
2021-01-27 11:06:09.009 [vert.x-worker-thread-2] [WARN ] {DriverDataSource:70} - Registered driver with driverClassName=oracle.jdbc.driver.OracleDriver was not found, trying direct instantiation.

I have 3 NamedDataSource:mysql 、mssql、oracle, when I startup clickhouse-jdbc-bridge, 3  NamedDataSource has the both  WARN:
 Registered driver with driverClassName=XXXXXX was not found, trying direct instantiation.
But the mysql and mssql can su connect to the database successfully, the oracle reports errors.

**Comment by gdnxdcs** [comment]
when the clickhouse-jdbc-bridge2.0 startup 45 second later ，it reports an error (ORA-00923: FROM keyword not found where expected). I guess the reason for the error is that the initialization test SQL statement does not add ‘from dual’， such as 'select 1 from dual',cause that  Failed to add NamedDataSource(id=oracle).

the details log:

2021-01-27 11:34:31.031 [vert.x-worker-thread-2] [WARN ] {DriverDataSource:70} - Registered driver with driverClassName=oracle.jdbc.driver.OracleDriver was not found, trying direct instantiation.
2021-01-27 11:35:15.015 [vert.x-worker-thread-2] [ERROR] {PoolBase:465} - oracle - Failed to execute connection test query (ORA-00923: FROM keyword not found where expected
).
2021-01-27 11:35:15.015 [vert.x-worker-thread-2] [ERROR] {HikariPool:497} - oracle - Error thrown while acquiring connection from data source
java.sql.SQLException: ORA-00923: FROM keyword not found where expected

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:439)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:395)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:802)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:436)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:186)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:521)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:194)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:853)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1145)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1267)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1882)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1847)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:301)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.executeSql(PoolBase.java:577)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.checkValidationSupport(PoolBase.java:461)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:441)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:410)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:363)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at ru.yandex.clickhouse.jdbcbridge.impl.JdbcDataSource.<init>(JdbcDataSource.java:437)
	at ru.yandex.clickhouse.jdbcbridge.impl.JdbcDataSource.newInstance(JdbcDataSource.java:296)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ru.yandex.clickhouse.jdbcbridge.core.Extension.newInstance(Extension.java:224)
	at ru.yandex.clickhouse.jdbcbridge.core.BaseRepository.createFromConfig(BaseRepository.java:97)
	at ru.yandex.clickhouse.jdbcbridge.core.BaseRepository.update(BaseRepository.java:209)
	at ru.yandex.clickhouse.jdbcbridge.impl.JsonFileRepository.reload(JsonFileRepository.java:94)
	at ru.yandex.clickhouse.jdbcbridge.JdbcBridgeVerticle.lambda$null$5(JdbcBridgeVerticle.java:584)
	at ru.yandex.clickhouse.jdbcbridge.internal.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at ru.yandex.clickhouse.jdbcbridge.internal.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at ru.yandex.clickhouse.jdbcbridge.internal.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2021-01-27 11:35:15.015 [vert.x-worker-thread-2] [ERROR] {HikariPool:593} - oracle - Exception during pool initialization.
java.sql.SQLException: ORA-00923: FROM keyword not found where expected

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:439)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:395)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:802)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:436)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:186)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:521)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:194)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:853)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1145)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1267)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1882)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1847)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:301)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.executeSql(PoolBase.java:577)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.checkValidationSupport(PoolBase.java:461)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:441)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:410)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:363)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at ru.yandex.clickhouse.jdbcbridge.impl.JdbcDataSource.<init>(JdbcDataSource.java:437)
	at ru.yandex.clickhouse.jdbcbridge.impl.JdbcDataSource.newInstance(JdbcDataSource.java:296)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ru.yandex.clickhouse.jdbcbridge.core.Extension.newInstance(Extension.java:224)
	at ru.yandex.clickhouse.jdbcbridge.core.BaseRepository.createFromConfig(BaseRepository.java:97)
	at ru.yandex.clickhouse.jdbcbridge.core.BaseRepository.update(BaseRepository.java:209)
	at ru.yandex.clickhouse.jdbcbridge.impl.JsonFileRepository.reload(JsonFileRepository.java:94)
	at ru.yandex.clickhouse.jdbcbridge.JdbcBridgeVerticle.lambda$null$5(JdbcBridgeVerticle.java:584)
	at ru.yandex.clickhouse.jdbcbridge.internal.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at ru.yandex.clickhouse.jdbcbridge.internal.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at ru.yandex.clickhouse.jdbcbridge.internal.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2021-01-27 11:35:15.015 [vert.x-worker-thread-2] [WARN ] {BaseRepository:222} - Failed to add NamedDataSource(id=oracle)
java.lang.IllegalStateException: Failed to create instance from extension: class ru.yandex.clickhouse.jdbcbridge.impl.JdbcDataSource
	at ru.yandex.clickhouse.jdbcbridge.core.Extension.newInstance(Extension.java:227)
	at ru.yandex.clickhouse.jdbcbridge.core.BaseRepository.createFromConfig(BaseRepository.java:97)
	at ru.yandex.clickhouse.jdbcbridge.core.BaseRepository.update(BaseRepository.java:209)
	at ru.yandex.clickhouse.jdbcbridge.impl.JsonFileRepository.reload(JsonFileRepository.java:94)
	at ru.yandex.clickhouse.jdbcbridge.JdbcBridgeVerticle.lambda$null$5(JdbcBridgeVerticle.java:584)
	at ru.yandex.clickhouse.jdbcbridge.internal.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at ru.yandex.clickhouse.jdbcbridge.internal.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at ru.yandex.clickhouse.jdbcbridge.internal.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: ORA-00923: FROM keyword not found where expected

	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:595)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:574)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at ru.yandex.clickhouse.jdbcbridge.impl.JdbcDataSource.<init>(JdbcDataSource.java:437)
	at ru.yandex.clickhouse.jdbcbridge.impl.JdbcDataSource.newInstance(JdbcDataSource.java:296)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ru.yandex.clickhouse.jdbcbridge.core.Extension.newInstance(Extension.java:224)
	... 10 more
Caused by: java.sql.SQLException: ORA-00923: FROM keyword not found where expected

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:439)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:395)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:802)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:436)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:186)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:521)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:194)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:853)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1145)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1267)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1882)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1847)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:301)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.executeSql(PoolBase.java:577)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.checkValidationSupport(PoolBase.java:461)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:441)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:410)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:363)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at ru.yandex.clickhouse.jdbcbridge.internal.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	... 19 more

**Comment by zhicwu** [comment]
You can add `connectionTestQuery` in your Oracle data source configuration file.  From example:
```json
   ... 
   "connectionTestQuery": " select 1 from dual", 
   ... 
```

**Comment by zhicwu** [comment]
Close due to no update more than a week - please feel free to re-open if the issue still exists.

**Comment by calebeaires** [comment]
@zhicwu you saved my day
